version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    working_dir: /code/carbalert
    command: gunicorn carbalert.wsgi -b 0.0.0.0:8000
    volumes:
      - "/static:/static"
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery_worker:
    build: .
    working_dir: /code
    command: python -m celery -A carbalert.carbalert_scrapy.carbalert_scrapy.tasks worker --loglevel=debug --max-tasks-per-child 1 --email "${MAILGUN_EMAIL}" --key ${MAILGUN_API_KEY} --domain ${MAILGUN_DOMAIN}
    depends_on:
      - web
      - redis

  celery_beat:
    build: .
    working_dir: /code
    command: python -m celery -A carbalert.carbalert_scrapy.carbalert_scrapy.tasks beat --loglevel=debug
    depends_on:
      - celery_worker 

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'

